---
peers:
  - aenode://pp$noKey@localhost:3015

keys:
  password: "top secret"
  dir: ./keys

chain:
  persist: true

mining:
  autostart: true
  expected_mine_rate: 15000
  cuckoo:
    miner:
      executable: mean16s-generic
      extra_args: ""
      node_bits: 16
